# https://www.appveyor.com/docs/appveyor-yml/

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format in appveyor
version: 'build_{build}-{branch}'

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

pull_requests:
  do_not_increment_build_number: true

# branches to build
branches:
  # whitelist
  only:
    - develop
    - master
    - production
    - /v\d*\.\d*\.\d*/
    - /^appveyor.*$/

  # blacklist
  except:
    - /^travis.*$/

# Do not build on tags (GitHub and BitBucket)
#skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
#skip_non_tags: true

# Skipping commits with particular message or from specific user
#skip_commits:
#  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/      # Regex for matching commit message
#  author: John                                      # Commit author's username, name, email or regexp maching one of these.

# Including commits with particular message or from specific user
#only_commits:
#  message: /build/                # Start a new build if message contains 'build'
#  author: jack@company.com        # Start a new build for commit of user with email jack@company.com

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
#skip_commits:
#  files:
#    - docs/*
#    - '**/*.html'

# Including commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
#only_commits:
#  files:
#    - Project-A/
#    - Project-B/

# Do not build feature branch with open Pull Requests
#skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
#max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2013

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\DownZemAll

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

# setting up etc\hosts file
#hosts:
#  queue-server: 127.0.0.1
#  db.server.com: 127.0.0.2

# custom environment variables
environment:
#  my_var1: value1
#  my_var2: value2
#  # this is how to set encrypted variable. Go to "Settings" -> "Encrypt YAML" page in account menu to encrypt data.
#  my_secure_var1:
#    secure: FW3tJ3fMncxvs58/ifSP7w==
#
# environment:
#  global:
#    connection_string: server=12;password=13;
#    service_url: https://127.0.0.1:8090
#
#  matrix:
#  - db: mysql
#    provider: mysql
#
#  - db: mssql
#    provider: mssql
#    password:
#      secure: $#(JFDA)jQ@#$

# this is how to allow failing jobs in the matrix
  matrix:
    - CMAKE_GENERATOR: "MinGW Makefiles"
      QT5: C:\Qt\5.7\mingw53_32
      COMPILER: mingw
#      platform: x86  # x86, x64, Any CPU
#      configuration: Release
#MinGW 5.3.0: C:\Qt\Tools\mingw530_32
#
# a faire: LLVM
#PATH --> C:\Program Files\LLVM\bin
#

# - CMAKE_GENERATOR: "Visual Studio 15 2017"
#    QT5: C:\Qt\5.12.2\mingw73_32
# - CMAKE_GENERATOR: "Visual Studio 15 2017"
#    QT5: C:\Qt\5.12\msvc2017
# - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
#    QT5: C:\Qt\5.12\msvc2017_64
#    - BUILD_TYPE: Release
#      COMPILER: MinGW
#      platform: Win32
#    - BUILD_TYPE: Release
#      COMPILER: MinGW-w64
#      platform: x64


# this is how to allow failing jobs in the matrix
#matrix:
#  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
#  allow_failures:
#    - platform: Any CPU
#      configuration: Release
#    - platform: x86
#      configuration: Release
#    - platform: x64
#      configuration: Debug


# exclude configuration from the matrix. Works similarly to 'allow_failures' 
# but build not even being started for excluded combination.
#  exclude:
#    - platform: x86
#      configuration: Debug

#  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
#


# build cache to preserve files/folders between builds
#cache:
#  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder
#                                    # but will reset it if packages.config is modified
#  - projectA\libs
#  - node_modules                    # local npm modules
#  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
#  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

# enable service required for build/tests
#services:
#  - mssql2014           # start SQL Server 2014 Express
#  - mssql2014rs         # start SQL Server 2014 Express and Reporting Services
#  - mssql2012sp1        # start SQL Server 2012 SP1 Express
#  - mssql2012sp1rs      # start SQL Server 2012 SP1 Express and Reporting Services
#  - mssql2008r2sp2      # start SQL Server 2008 R2 SP2 Express
#  - mssql2008r2sp2rs    # start SQL Server 2008 R2 SP2 Express and Reporting Services
#  - mysql               # start MySQL 5.6 service
#  - postgresql          # start PostgreSQL 9.5 service
#  - iis                 # start IIS
#  - msmq                # start Queuing services
#  - mongodb             # start MongoDB

# scripts that run after cloning repository
install:
#  # by default, all script lines are interpreted as batch
#  - echo This is batch
#  # to run script as a PowerShell command prepend it with ps:
#  - ps: Write-Host 'This is PowerShell'
#  # batch commands start from cmd:
#  - cmd: echo This is batch again
#  - cmd: set MY_VAR=12345

  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set Qt5_DIR=C:\Qt\5.7\mingw53_32\lib\cmake\Qt5
  - set PATH=%PATH%;C:\Qt\Tools\mingw530_32\bin\
  #- set PATH=%PATH%;C:\Qt\5.7\mingw53_32\bin\
  #- set PATH=%PATH%;C:\Qt\5.7\mingw53_32\plugins\

  # replace all ';' by '\n' in PATH so that it's easier to read
  - echo PATH = & echo.    %PATH:;= & echo.    %  

  # Rename sh.exe as sh2.exe otherwise its PATH interferes with MinGW
  - rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"

  # read the content of the file ./version
  - set /p AppVersion=<version
  - echo Application Version = %AppVersion%

  - gcc.exe -dumpmachine > tmp
  - set /p GCCDumpMachine=<tmp
  - g++.exe -dumpmachine > tmp
  - set /p GPPDumpMachine=<tmp
  - echo "GCC Dump Machine = '${GCCDumpMachine}'"
  - echo "G++ Dump Machine = '${GPPDumpMachine}'"

#  - if [%COMPILER%]==[MinGW] set PATH=C:\MinGW\bin;%PATH%
#  - if [%COMPILER%]==[MinGW] mingw-get update


# enable patching of AssemblyInfo.* files
#assembly_info:
#  patch: true
#  file: AssemblyInfo.*
#  assembly_version: "2.2.{build}"
#  assembly_file_version: "{version}"
#  assembly_informational_version: "{version}"

# Automatically register private account and/or project AppVeyor NuGet feeds.
#nuget:
#  account_feed: true
#  project_feed: true
#  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to account/project feeds for pull request builds
#  publish_wap_octopus: true       # disable publishing of Octopus Deploy .nupkg artifacts to account/project feeds


#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
#  parallel: true                  # enable MSBuild parallel builds
#  project: MyTestAzureCS.sln      # path to Visual Studio solution or project
#  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy
#  publish_wap_xcopy: true         # package Web Application Projects (WAP) for XCopy deployment
#  publish_wap_beanstalk: true     # Package Web Applications for AWS Elastic Beanstalk deployment
#  publish_wap_octopus: true       # Package Web Applications for Octopus deployment
#  publish_azure_webjob: true      # Package Azure WebJobs for Zip Push deployment
#  publish_azure: true             # package Azure Cloud Service projects and push to artifacts
#  publish_aspnet_core: true       # Package ASP.NET Core projects
#  publish_core_console: true      # Package .NET Core console projects
#  publish_nuget: true             # package projects with .nuspec files and push to artifacts
#  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
#  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
#
#  # MSBuild verbosity level
#  verbosity: quiet|minimal|normal|detailed


# scripts to run before build
before_build:
  # Current Directory = C:\projects\DownZemAll
  - mkdir ".\..\build-cmake" -f
  - cd ".\..\build-cmake"

# to run your custom scripts instead of automatic MSBuild
build_script:
  - echo ****************************************************
  - echo Building executables (application and tests)
  - echo ****************************************************
  - cmake --version         # version 3.12.2
  - cmake .\..\DownZemAll -G "%CMAKE_GENERATOR%" -DCMAKE_PREFIX_PATH="%QT5%" -DCMAKE_INSTALL_PREFIX=".\..\install-DownZemAll-cmake" -DENABLE_TESTS=ON
  - cmake --build .


# scripts to run after build (working directory and environment changes are 
# persisted from the previous steps)
after_build:

# scripts to run *after* solution is built and *before* automatic packaging 
# occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# to disable automatic builds
# build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run tests against only selected assemblies and/or categories
test:
#  assemblies:
#    only:
#      - asm1.dll
#      - asm2.dll
#
#  categories:
#    only:
#      - UI
#      - E2E

# to run tests against all except selected assemblies and/or categories
#test:
#  assemblies:
#    except:
#      - asm1.dll
#      - asm2.dll
#
#  categories:
#    except:
#      - UI
#      - E2E

# to run tests from different categories as separate jobs in parallel
#test:
#  categories:
#    - A            # A category common for all jobs
#    - [UI]         # 1st job
#    - [DAL, BL]    # 2nd job

#---------------------------------#
#            tests                #
#---------------------------------#

# scripts to run before tests (working directory and environment changes
# are persisted from the previous steps such as "before_build")
before_test:

# to run your custom scripts instead of automatic tests
test_script:
  - ctest --version
  - ctest -N                # -N gets the list of all the tests in CTest
  - ctest . --verbose       # <verbose> shows all the test methods


#---------------------------------#
#           archives              #
#---------------------------------#

# scripts to run after tests
after_test:
  - cmake --build . --target install
  - mkdir C:\projects\DownZemAll\bin
  - cd C:\projects\DownZemAll\bin

# zip the files
# DownZemAll_v1.2.0_x86-windows-mingw.zip
# DownZemAll_v1.2.0_x86_64-linux-gnu.tar.gz
  - set ZIP_FILE="DownZemAll_v%AppVersion%_%PLATFORM%-windows-%COMPILER%.zip"
  - 7z a %ZIP_FILE% .\..\..\install-DownZemAll-cmake\*


# to disable automatic tests
# test: off

#---------------------------------#
#    artifacts configuration      #
#---------------------------------#

artifacts: 
   # pushing *.zip files in install directory
  - path: 'bin\*.zip'
    name: myapp

#  # pushing a single file
#  - 'path: C:\projects\*.zip'
#
#  # pushing a single file with environment variable in path and "Deployment name" specified
#  - path: MyProject\bin\$(configuration)
#    name: myapp
#
#  # pushing entire folder as a zip archive
#  - path: logs
#
#  # pushing all *.nupkg files in build directory recursively
#  - path: '**\*.nupkg'


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# HOW-TO GITHUB
# 1. Add new tag in local repo.
# 2. Push tag to GitHub repo and start a new AppVeyor build.
# 3. AppVeyor creates a new (draft) release based on that tag and uploads artifacts.


# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
  - provider: GitHub
    tag: v%AppVersion%
    release: DownZemAll v%AppVersion%
    # mandatory description (use '' if any) otherwise GitHub  "422: Unprocessable entity" error
    description: 'Draft release of DownZemAll version %AppVersion% (build $(appveyor_build_version))' 
    auth_token:
      secure: 8tIRAglcbx9Yw8zLDDQnrdk/Fk/az61lSIykfvzqPApy6LFxjTHoUJW8gYDGKgsq
    artifact: myapp
    draft: true
    prerelease: false
#    force_update: true
    on:
#      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only

#     # FTP deployment provider settings
#   - provider: FTP
#     protocol: ftp|ftps|sftp
#     host: ftp.myserver.com
#     username: admin
#     password:
#       secure: eYKZKFkkEvFYWX6NfjZIVw==
#     folder:
#     application:
#     active_mode: false
#     beta: true      # enable alternative FTP library for 'ftp' and 'ftps' modes
#     debug: true     # show complete FTP log
# 
#     # Amazon S3 deployment provider settings
#   - provider: S3
#     access_key_id:
#       secure: ABcd==
#     secret_access_key:
#       secure: ABcd==
#     bucket: my_bucket
#     folder:
#     artifact:
#     set_public: false
# 
#     # Azure Blob storage deployment provider settings
#   - provider: AzureBlob
#     storage_account_name:
#       secure: ABcd==
#     storage_access_key:
#       secure: ABcd==
#     container: my_container
#     folder:
#     artifact:
# 
#     # Web Deploy deployment provider settings
#   - provider: WebDeploy
#     server: http://www.deploy.com/myendpoint
#     website: mywebsite
#     username: user
#     password:
#       secure: eYKZKFkkEvFYWX6NfjZIVw==
#     ntlm: false
#     remove_files: false
#     app_offline: false
#     do_not_use_checksum: true           # do not use check sum for comparing source and destination files. By default checksums are used.
#     sync_retry_attempts: 2              # sync attempts, max
#     sync_retry_interval: 2000           # timeout between sync attempts, milliseconds
#     aspnet_core: true                   # artifact zip contains ASP.NET Core application
#     aspnet_core_force_restart: true     # poke app's web.config before deploy to force application restart
#     skip_dirs: \\App_Data
#     skip_files: web.config
#     on:
#       branch: release
#       platform: x86
#       configuration: debug
# 
#     # Deploying to Azure Cloud Service
#   - provider: AzureCS
#     subscription_id:
#       secure: fjZIVw==
#     subscription_certificate:
#       secure: eYKZKFkkEv...FYWX6NfjZIVw==
#     storage_account_name: my_storage
#     storage_access_key:
#       secure: ABcd==
#     service: my_service
#     slot: Production
#     target_profile: Cloud
#     artifact: MyPackage.cspkg
# 
#     # Deploying to NuGet feed
#   - provider: NuGet
#     server: https://my.nuget.server/feed
#     api_key:
#       secure: FYWX6NfjZIVw==
#     skip_symbols: false
#     symbol_server: https://your.symbol.server/feed
#     artifact: MyPackage.nupkg
# 
#     # Deploy to GitHub Releases
#   - provider: GitHub
#     artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
#     draft: false
#     prerelease: false
#     on:
#       branch: master                # release from master branch only
#       APPVEYOR_REPO_TAG: true       # deploy on tag push only
#
#     # Deploying to a named environment
#   - provider: Environment
#     name: staging
#     on:
#       branch: staging
#       env_var1: value1
#       env_var2: value2


# scripts to run before deployment
before_deploy:

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:
 
# to disable deployment
#deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
#on_success:
#  - do something

# on build failure
#on_failure:
#  - do something

# after build failure or success
#on_finish:
#  - do something


#---------------------------------#
#         notifications           #
#---------------------------------#

#notifications:
#
#  # Email
#  - provider: Email
#    to:
#      - user1@email.com
#      - user2@email.com
#    subject: 'Build {{status}}'                  # optional
#    message: "{{message}}, {{commitId}}, ..."    # optional
#    on_build_status_changed: true
#
#  # HipChat
#  - provider: HipChat
#    auth_token:
#      secure: RbOnSMSFKYzxzFRrxM1+XA==
#    room: ProjectA
#    template: "{message}, {commitId}, ..."
#
#  # Slack
#  - provider: Slack
#    incoming_webhook: http://incoming-webhook-url
#
#  # ...or using auth token
#
#  - provider: Slack
#    auth_token:
#      secure: kBl9BlxvRMr9liHmnBs14A==
#    channel: development
#    template: "{message}, {commitId}, ..."
#
#  # Campfire
#  - provider: Campfire
#    account: appveyor
#    auth_token:
#      secure: RifLRG8Vfyol+sNhj9u2JA==
#    room: ProjectA
#    template: "{message}, {commitId}, ..."
#
#  # Webhook
#  - provider: Webhook
#    url: http://www.myhook2.com
#    headers:
#      User-Agent: myapp 1.0
#      Authorization:
#        secure: GhD+5xhLz/tkYY6AO3fcfQ==
#    on_build_success: false
#    on_build_failure: true
#    on_build_status_changed: true
#
