# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            ArrowDL
tagline:          'ArrowDL'
description:      '<a href="https://www.arrow-dl.com/ArrowDL" target="_blank">ArrowDL</a> is a download manager for Windows, Mac OS X and Linux.'
url:              https://www.arrow-dl.com
baseurl:          '/ArrowDL'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'SetVisible(0!=1)'
  url:            https://www.arrow-dl.com

github:
  repo:           https://github.com/setvisible/ArrowDL

paginate:         5
                  # paginate means 5 posts max per page

paginate_path:    '/news/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
sidebar_blog_link:  '/news'     # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
